# Generated by Django 4.2.11 on 2025-05-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_customuser_storage_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="storage_limit",
            field=models.BigIntegerField(default=8589934592),
        ),
    ]
